services:
  db:
    image: postgres:15
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  backend:
    build: .

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SCHEMA: public
      DATABASE_SSL: false

      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "1337:1337"

    volumes:
      - .:/opt/app
      - /opt/app/node_modules

    depends_on:
      - db

  seeder-data:
    build: .

    env_file:
      - .env

    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SCHEMA: public
      DATABASE_SSL: false

    command: >
      sh -c 'npm run seed:data'

    volumes:
      - .:/opt/app
      - /opt/app/node_modules

    depends_on:
      - backend

  seeder-admin:
    build: .

    env_file:
      - .env

    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SCHEMA: public
      DATABASE_SSL: false

    command: >
      sh -c 'npm run seed:admin'

    volumes:
      - .:/opt/app
      - /opt/app/node_modules

    depends_on:
      - seeder-data

volumes:
  db_data:
    driver: local